PMDA++: pcp::instance_domain Class Reference
pcp::instance_domain Class Reference
Performance metric instance domain.
#include <instance_domain.hpp>
Public Member Functions
domain_id_type get_domain_id () const
Get this instance domain's user-defined ID.
pmInDom get_pm_instance_domain () const
Get this instance domain's PCP-modifed ID.
void set_domain_id (const domain_id_type id)
Set this instance domain's user-defined ID.
void set_pm_instance_domain (const pmInDom domain)
Set this instance domain's PCP-modified ID.
instance_domain & operator() (const domain_id_type domain_id)
Functor for setting this instance's domain ID.
instance_domain & operator() (const instance_id_type instance_id, const instance_info &info)
Instance insertion functor.
instance_domain & operator() (const instance_id_type instance_id, const std::string &instance_name, const std::string &short_description=std::string(), const std::string &verbose_description=std::string())
Instance insertion functor.
operator pmInDom () const
Operator for implicit cast to pmInDom.
Detailed Description
Performance metric instance domain.
Definition at line 35 of file instance_domain.hpp.
Member Function Documentation
domain_id_type pcp::instance_domain::get_domain_id () const inline
Get this instance domain's user-defined ID.
Returns
This instance domain's user-defined ID.
See Also
set_domain_id
Definition at line 46 of file instance_domain.hpp.
Referenced by pcp::pmda::initialize_pmda().
pmInDom pcp::instance_domain::get_pm_instance_domain () const inline
Get this instance domain's PCP-modifed ID.
This function is used to track the instance ID as modifed by PCP's pmdaInit function. This is essentially the same as the ID returned by get_domain_id, with a number of higher bits set to PCP-internal values.
This can be necessary for passing this instance domain's ID to some other PCP built-in functions.
Returns
This instance domain's PCP-modifed ID.
See Also
set_pm_instance_domain
pmdaInit
Definition at line 66 of file instance_domain.hpp.
Referenced by pcp::pmda::initialize_pmda().
pcp::instance_domain::operator pmInDom () const inline
Operator for implicit cast to pmInDom.
This operator allows this object to be used wherever PCP functions require a pmInDom instance. It is equivalent to calling the get_pm_instance_domain function.
Returns
This instance's PCP-modified ID.
Definition at line 164 of file instance_domain.hpp.
instance_domain& pcp::instance_domain::operator() (const domain_id_type domain_id) inline
Functor for setting this instance's domain ID.
This functor is equivalent to the set_domain_id function, but allows for convenient functor chaining.
Parameters
domain_id ID for the instance domain.
Returns
A reference to this instance domain.
Definition at line 104 of file instance_domain.hpp.
References set_domain_id(), and set_pm_instance_domain().
instance_domain& pcp::instance_domain::operator() (const instance_id_type instance_id, const instance_info & info) inline
Instance insertion functor.
This functor allows for convenient insertion of instances into this domain.
Parameters
instance_id ID for the instance to insert.
info Basic instance information.
Returns
A reference to this instance domain.
Definition at line 122 of file instance_domain.hpp.
instance_domain& pcp::instance_domain::operator() (const instance_id_type instance_id, const std::string & instance_name, const std::string & short_description = std::string(), const std::string & verbose_description = std::string()) inline
Instance insertion functor.
This functor allows for convenient insertion of instances into this domain.
Parameters
instance_id ID for the instance to insert.
instance_name Name of the instance to insert.
short_description Short description of the instance to insert.
verbose_description Verbose description of the instance to insert.
Returns
A reference to this instance domain.
Definition at line 142 of file instance_domain.hpp.
References pcp::instance_info::instance_name, pcp::instance_info::short_description, and pcp::instance_info::verbose_description.
void pcp::instance_domain::set_domain_id (const domain_id_type id) inline
Set this instance domain's user-defined ID.
Parameters
id The domiain ID to set.
Definition at line 76 of file instance_domain.hpp.
Referenced by operator()().
void pcp::instance_domain::set_pm_instance_domain (const pmInDom domain) inline
Set this instance domain's PCP-modified ID.
This normally used by the pcp::pmda class to update the domain ID after invoking pmdaInit.
Parameters
domain The domiain ID to set.
Definition at line 89 of file instance_domain.hpp.
Referenced by pcp::pmda::initialize_pmda(), and operator()().
The documentation for this class was generated from the following file:
instance_domain.hpp