PMDA++: pcp::metric_cluster Class Reference
pcp::metric_cluster Class Reference
A cluster of metric descriptions.
#include <metric_description.hpp>
Public Member Functions
metric_cluster (const cluster_id_type id, const std::string &name)
Constructor.
cluster_id_type get_cluster_id () const
Get this cluster's ID.
std::string get_cluster_name () const
Get this cluster's name.
metric_cluster & operator() (const item_id_type item_id, const std::string &metric_name, const atom_type_type type, const semantic_type semantic, const pmUnits &units, const metric_flags flags=static_cast< metric_flags >(0), instance_domain *const domain=NULL, const std::string &short_description=std::string(), const std::string &verbose_description=std::string(), void *const opaque=NULL)
Metric insertion functor.
metric_cluster & operator() (const item_id_type item_id, const std::string &metric_name, const atom_type_type type, const semantic_type semantic, const pmUnits &units, instance_domain *const domain, const metric_flags flags=static_cast< metric_flags >(0), const std::string &short_description=std::string(), const std::string &verbose_description=std::string(), void *const opaque=NULL)
Metric insertion functor.
metric_cluster & operator() (const item_id_type item_id, const std::string &metric_name, const atom_type_type type, const semantic_type semantic, const pmUnits &units, instance_domain *const domain=NULL, const std::string &short_description=std::string(), const std::string &verbose_description=std::string(), void *const opaque=NULL, const metric_flags flags=static_cast< metric_flags >(0))
Metric insertion functor.
Detailed Description
A cluster of metric descriptions.
Definition at line 126 of file metric_description.hpp.
Constructor & Destructor Documentation
metric_cluster()
pcp::metric_cluster::metric_cluster (const cluster_id_type id, const std::string & name) inline
Constructor.
Parameters
id ID for this cluster.
name Name for this cluster.
Definition at line 136 of file metric_description.hpp.
Member Function Documentation
get_cluster_id()
cluster_id_type pcp::metric_cluster::get_cluster_id () const inline
Get this cluster's ID.
Returns
This cluster's ID.
Definition at line 149 of file metric_description.hpp.
Referenced by pcp::pmda::initialize_pmda(), and pcp::pmda::set_callbacks().
get_cluster_name()
std::string pcp::metric_cluster::get_cluster_name () const inline
Get this cluster's name.
Returns
This cluster's name.
Definition at line 159 of file metric_description.hpp.
Referenced by pcp::pmda::set_callbacks().
operator()() [1/3]
metric_cluster& pcp::metric_cluster::operator() (const item_id_type item_id, const std::string & metric_name, const atom_type_type type, const semantic_type semantic, const pmUnits & units, const metric_flags flags = static_cast<metric_flags>(0), instance_domain *const domain = NULL, const std::string & short_description = std::string(), const std::string & verbose_description = std::string(), void *const opaque = NULL) inline
Metric insertion functor.
This functor allows for chained insertion of metrics into this cluster.
Parameters
item_id ID for the metric being inserted.
metric_name Metric name.
type Atom type.
semantic PCP semantic.
units PCP units.
flags Optional metric flags.
domain Optional instance domain.
short_description Short description.
verbose_description Verbose description.
opaque Opaque value to track.
Returns
A reference to this metric cluster.
Definition at line 182 of file metric_description.hpp.
References pcp::metric_description::metric_description().
operator()() [2/3]
metric_cluster& pcp::metric_cluster::operator() (const item_id_type item_id, const std::string & metric_name, const atom_type_type type, const semantic_type semantic, const pmUnits & units, instance_domain *const domain, const metric_flags flags = static_cast<metric_flags>(0), const std::string & short_description = std::string(), const std::string & verbose_description = std::string(), void *const opaque = NULL) inline
Metric insertion functor.
This functor allows for chained insertion of metrics into this cluster.
Parameters
item_id ID for the metric being inserted.
metric_name Metric name.
type Atom type.
semantic PCP semantic.
units PCP units.
domain Optional instance domain.
flags Optional metric flags.
short_description Short description.
verbose_description Verbose description.
opaque Opaque value to track.
Returns
A reference to this metric cluster.
Definition at line 216 of file metric_description.hpp.
References pcp::metric_description::metric_description().
operator()() [3/3]
metric_cluster& pcp::metric_cluster::operator() (const item_id_type item_id, const std::string & metric_name, const atom_type_type type, const semantic_type semantic, const pmUnits & units, instance_domain *const domain = NULL, const std::string & short_description = std::string(), const std::string & verbose_description = std::string(), void *const opaque = NULL, const metric_flags flags = static_cast<metric_flags>(0)) inline
Metric insertion functor.
This functor allows for chained insertion of metrics into this cluster.
Parameters
item_id ID for the metric being inserted.
metric_name Metric name.
type Atom type.
semantic PCP semantic.
units PCP units.
domain Optional instance domain.
short_description Short description.
verbose_description Verbose description.
opaque Opaque value to track.
flags Optional metric flags.
Returns
A reference to this metric cluster.
Definition at line 250 of file metric_description.hpp.
References pcp::metric_description::metric_description().
The documentation for this class was generated from the following file:
metric_description.hpp