PMDA++: pcp Namespace Reference
pcp Namespace Reference
Namespaces
cache
Classes
class exception
Base class for all PMDA++ exceptions.
class instance_domain
Performance metric instance domain.
struct instance_info
Basic instance domain information.
class metric_cluster
A cluster of metric descriptions.
struct metric_description
Individual metric description.
class metrics_description
Collection of clusters of metric descriptions.
class pmda
Abstract base class for implementing PCP PMDAs.
Typedefs
typedef uint_fast8_t atom_type_type
PM_TYPE_* (0 - 9)
typedef uint_fast16_t cluster_id_type
__pmID_int::cluster (12-bits)
typedef uint_fast16_t domain_id_type
__pmID_int::cluster (9-bits); pmdaIndom::it_indom
typedef unsigned int instance_id_type
https://github.com/pcolby/pcp-pmda-cpp/issues/11
typedef uint_fast16_t item_id_type
__pmID_int::item (10-bits)
typedef uint_fast8_t semantic_type
PM_SEM_* (0 - 4)
Enumerations
enum metric_flags { storable_metric = 0x1 }
Flags that may be applied to metric descriptions.
Functions
template<typename ValueType >
pmAtomValue atom (const atom_type_type type, ValueType value)
Caset a value to a PCP pmAtomValue.
template<>
pmAtomValue atom< char * > (const atom_type_type type, char *value)
Caset a value to a PCP pmAtomValue.
template<>
pmAtomValue atom< pmValueBlock * > (const atom_type_type type, pmValueBlock *value)
Caset a value to a PCP pmAtomValue.
template<typename Type >
Type get_pcp_runtime_version ()
Get the PCP runtime version as a numeric value.
template<>
char * get_pcp_runtime_version ()
Get the PCP runtime version as a string.
metric_flags operator| (metric_flags a, metric_flags b)
Pipe operator for combining metric_flags values.
template<typename Type >
atom_type_type type ()
Get the PM_TYPE_* constant for a given C++ type.
template<>
atom_type_type type< int8_t > ()
Template specialisation for int8_t.
template<>
atom_type_type type< int16_t > ()
Template specialisation for int16_t.
template<>
atom_type_type type< int32_t > ()
Template specialisation for int32_t.
template<>
atom_type_type type< int64_t > ()
Template specialisation for int64_t.
template<>
atom_type_type type< uint8_t > ()
Template specialisation for uint8_t.
template<>
atom_type_type type< uint16_t > ()
Template specialisation for uint16_t.
template<>
atom_type_type type< uint32_t > ()
Template specialisation for uint32_t.
template<>
atom_type_type type< uint64_t > ()
Template specialisation for uint64_t.
template<>
atom_type_type type< float > ()
Template specialisation for float.
template<>
atom_type_type type< double > ()
Template specialisation for double.
template<>
atom_type_type type< char * > ()
Template specialisation for char *.
template<>
atom_type_type type< std::string > ()
Template specialisation for std::string.
template<typename Type >
pmUnits units (Type a, Type b, Type c, Type d, Type e, Type f)
Wrapper for PMDA_PMUNITS.
Typedef Documentation
typedef uint_fast8_t pcp::atom_type_type
PM_TYPE_* (0 - 9)
Definition at line 22 of file types.hpp.
typedef uint_fast16_t pcp::cluster_id_type
__pmID_int::cluster (12-bits)
Definition at line 23 of file types.hpp.
typedef uint_fast16_t pcp::domain_id_type
__pmID_int::cluster (9-bits); pmdaIndom::it_indom
Definition at line 24 of file types.hpp.
typedef unsigned int pcp::instance_id_type
https://github.com/pcolby/pcp-pmda-cpp/issues/11
Definition at line 25 of file types.hpp.
typedef uint_fast16_t pcp::item_id_type
__pmID_int::item (10-bits)
Definition at line 26 of file types.hpp.
typedef uint_fast8_t pcp::semantic_type
PM_SEM_* (0 - 4)
Definition at line 27 of file types.hpp.
Enumeration Type Documentation
enum pcp::metric_flags
Flags that may be applied to metric descriptions.
Enumerator
storable_metric
Metric supports pmstore operations.
Definition at line 30 of file metric_description.hpp.
Function Documentation
template<typename ValueType > pmAtomValue pcp::atom (const atom_type_type type, ValueType value)
Caset a value to a PCP pmAtomValue.
This base template definition handles most numeric types.
Parameters
type The atom type to set.
value The atom value to set.
Template Parameters
ValueType Type of value to set.
Returns
A pmAtomValue containing value of type type.
Definition at line 35 of file atom.hpp.
Referenced by atom< char * >(), and atom< pmValueBlock * >().
template<> pmAtomValue pcp::atom< char * > (const atom_type_type type, char * value) inline
Caset a value to a PCP pmAtomValue.
This template specialisation hanldes char * strings.
Note
We do not provide a const char * template specialisation, since that would require us to const_cast the value, which is something the caller ought to be very clear about / aware is happening. Hence, if you want to use a const char *, use something like: pcp::atom(PM_TYPE_STRING, const_cast<char *>(value)
Parameters
type The atom type to set.
value The atom value to set.
Returns
A pmAtomValue containing value of type type.
Definition at line 73 of file atom.hpp.
References atom().
template<> pmAtomValue pcp::atom< pmValueBlock * > (const atom_type_type type, pmValueBlock * value) inline
Caset a value to a PCP pmAtomValue.
This template specialisation hanldes pmValueBlock values.
Parameters
type The atom type to set.
value The atom value to set.
Returns
A pmAtomValue containing value of type type.
Definition at line 105 of file atom.hpp.
References atom().
template<typename Type > Type pcp::get_pcp_runtime_version () inline
Get the PCP runtime version as a numeric value.
Returns
The PCP runtime version as a numeric value.
Definition at line 77 of file config.hpp.
template<> char* pcp::get_pcp_runtime_version () inline
Get the PCP runtime version as a string.
Returns
The PCP runtime version as a string.
Definition at line 92 of file config.hpp.
metric_flags pcp::operator| (metric_flags a, metric_flags b) inline
Pipe operator for combining metric_flags values.
This function performs a logical OR of two metric_flags sets. This is a convenience function, allowing metric_flags enum values to be used both standalone, and in combination.
Parameters
a First set of flags.
b Second set of flags.
Returns
Combined set of both a and b flags.
Definition at line 46 of file metric_description.hpp.
template<typename Type > atom_type_type pcp::type () inline
Get the PM_TYPE_* constant for a given C++ type.
Referenced by pcp::pmda::set_callbacks().
template<> atom_type_type pcp::type< char * > () inline
Template specialisation for char *.
Definition at line 47 of file types.hpp.
template<> atom_type_type pcp::type< double > () inline
Template specialisation for double.
Definition at line 44 of file types.hpp.
template<> atom_type_type pcp::type< float > () inline
Template specialisation for float.
Definition at line 43 of file types.hpp.
template<> atom_type_type pcp::type< int16_t > () inline
Template specialisation for int16_t.
Definition at line 34 of file types.hpp.
template<> atom_type_type pcp::type< int32_t > () inline
Template specialisation for int32_t.
Definition at line 35 of file types.hpp.
template<> atom_type_type pcp::type< int64_t > () inline
Template specialisation for int64_t.
Definition at line 36 of file types.hpp.
template<> atom_type_type pcp::type< int8_t > () inline
Template specialisation for int8_t.
Definition at line 33 of file types.hpp.
template<> atom_type_type pcp::type< std::string > () inline
Template specialisation for std::string.
Definition at line 48 of file types.hpp.
template<> atom_type_type pcp::type< uint16_t > () inline
Template specialisation for uint16_t.
Definition at line 38 of file types.hpp.
template<> atom_type_type pcp::type< uint32_t > () inline
Template specialisation for uint32_t.
Definition at line 39 of file types.hpp.
template<> atom_type_type pcp::type< uint64_t > () inline
Template specialisation for uint64_t.
Definition at line 40 of file types.hpp.
template<> atom_type_type pcp::type< uint8_t > () inline
Template specialisation for uint8_t.
Definition at line 37 of file types.hpp.
template<typename Type > pmUnits pcp::units (Type a, Type b, Type c, Type d, Type e, Type f) inline
Wrapper for PMDA_PMUNITS.
This allows C++11-style initialisation lists, while avoiding C++ "extended initializer lists" warnings.
Parameters
a The first argument to pass to the PMDA_PMUNITS macro.
b The second argument to pass to the PMDA_PMUNITS macro.
d The third argument to pass to the PMDA_PMUNITS macro.
d The fourth argument to pass to the PMDA_PMUNITS macro.
e The fifth argument to pass to the PMDA_PMUNITS macro.
f The sixth argument to pass to the PMDA_PMUNITS macro.
Returns
A pmUnits value constructed from the supplied arguments.
Definition at line 38 of file units.hpp.